In [1]:
import pandas as pd
import numpy as np

In [2]:
ls

Aggregate.ipynb               Hackathon_Mobile_Data.xlsx
Hackathon.ipynb               Hackathon_SEM_Diagram.png
Hackathon.pdf                 SEM-Copy1.ipynb
Hackathon_Data_Full.xlsx      SEM.ipynb
Hackathon_Data_Full_agg.xlsx  Untitled.ipynb
Hackathon_Data_Full_v2.xlsx   data.csv
Hackathon_Desktop_Data.xlsx

In [3]:
df = pd.read_excel('Hackathon_Data_Full_agg.xlsx')
df

,Day,Page Views,Visits,Unique Visitors,Find Dealer (1),BP: Finish (2),Vehicle Quote (3),Brochure Postal (5),BP: Start (6),Trade-Ins (8),...,Payment Estimator (21),Click to Call (27),Average Pages per Visit,Average Time on Site,Search-natural Visits,Typed-bookmarked Visits,Search-paid visits,Banner visits,Vehicle Home visits,Gallery visits
0,2020-07-01,287473,71908,64563,800,7866,107,0,14352,14,...,8067,3,3.997789,377.434487,11736,13865,8846,29029,9630,1236
1,2020-07-02,300343,76825,68604,1076,7800,116,0,14679,34,...,8159,28,3.909444,371.873767,12572,16079,9200,31176,10059,1296
2,2020-07-03,291782,73826,66158,981,7701,112,0,14652,17,...,7470,30,3.952293,373.958955,10040,13643,11368,27494,12213,1485
3,2020-07-04,266314,67019,59750,769,7086,82,0,13443,22,...,6772,7,3.973709,381.409387,9452,10967,11084,28035,11015,1365
4,2020-07-05,275161,67302,60045,814,7570,92,0,14032,15,...,7324,16,4.088452,390.358692,10893,12097,11356,26167,10542,1463
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,2022-06-26,346974,62079,54510,661,13189,88,0,16736,16,...,6201,1,5.589233,381.785490,14809,11197,7839,16795,10039,737
726,2022-06-27,387627,74636,64794,1096,13994,130,0,18068,21,...,6725,49,5.193566,392.073554,15812,15066,8043,22489,9823,796
727,2022-06-28,367451,67688,58344,961,13596,151,0,17458,21,...,6504,20,5.428599,386.791620,15095,14621,8002,17141,9461,740
728,2022-06-29,363136,69834,60531,976,13290,132,0,17206,21,...,6350,30,5.199989,387.564905,14444,13959,8512,20400,9626,676
729,2022-06-30,313449,58944,50941,891,11687,94,0,15307,18,...,5483,21,5.317742,375.471924,13070,12985,7763,13096,9132,674

In [4]:
df.columns

Index(['Day', 'Page Views', 'Visits', 'Unique Visitors', 'Find Dealer (1)',
       'BP: Finish (2)', 'Vehicle Quote (3)', 'Brochure Postal (5)',
       'BP: Start (6)', 'Trade-Ins (8)', 'Incentive Views (9)',
       'Comp. Compare (12)', 'Brochure PDF (15)', 'Quick Quotes (18)',
       'Search Inventory (19)', 'Test Drive (20)', 'Payment Estimator (21)',
       'Click to Call  (27)', 'Average Pages per Visit',
       'Average Time on Site', 'Search-natural Visits',
       'Typed-bookmarked Visits', 'Search-paid visits', 'Banner visits',
       'Vehicle Home visits', 'Gallery visits'],
      dtype='object')

In [5]:
df = df.drop(columns=['Page Views', 'Visits', 'Unique Visitors', 'Brochure Postal (5)', 'Comp. Compare (12)', 'Brochure PDF (15)']).set_index(['Day'])

In [6]:
df.columns

Index(['Find Dealer (1)', 'BP: Finish (2)', 'Vehicle Quote (3)',
       'BP: Start (6)', 'Trade-Ins (8)', 'Incentive Views (9)',
       'Quick Quotes (18)', 'Search Inventory (19)', 'Test Drive (20)',
       'Payment Estimator (21)', 'Click to Call  (27)',
       'Average Pages per Visit', 'Average Time on Site',
       'Search-natural Visits', 'Typed-bookmarked Visits',
       'Search-paid visits', 'Banner visits', 'Vehicle Home visits',
       'Gallery visits'],
      dtype='object')

In [7]:
df = df.rename(columns={'Find Dealer (1)':'findDealer', 'BP: Finish (2)':'bpFinish', 'Vehicle Quote (3)':'vehQuote',
       'Brochure Postal (5)':'brochurePostal', 'BP: Start (6)':'bpStart', 'Trade-Ins (8)':'tradeIn',
       'Incentive Views (9)':'incView', 'Comp. Compare (12)':'compCompare', 'Brochure PDF (15)':'brochurePDF',
       'Quick Quotes (18)':'quickQuote', 'Search Inventory (19)':'searchInv', 'Test Drive (20)':'testDrive',
       'Payment Estimator (21)':'paymentEst', 'Click to Call  (27)':'clickCall',
       'Average Pages per Visit':'avgPageVis', 'Average Time on Site':'avgSiteTime',
       'Search-natural Visits':'naturalSearchVis', 'Typed-bookmarked Visits':'bookmarkedVis',
       'Search-paid visits':'paidSearchVis', 'Banner visits':'bannerVis', 'Vehicle Home visits':'vehHomeVis',
       'Gallery visits':'galleryVis'})

In [8]:
df

,findDealer,bpFinish,vehQuote,bpStart,tradeIn,incView,quickQuote,searchInv,testDrive,paymentEst,clickCall,avgPageVis,avgSiteTime,naturalSearchVis,bookmarkedVis,paidSearchVis,bannerVis,vehHomeVis,galleryVis
Day,,,,,,,,,,,,,,,,,,,
2020-07-01,800,7866,107,14352,14,5021,13,1181,6,8067,3,3.997789,377.434487,11736,13865,8846,29029,9630,1236
2020-07-02,1076,7800,116,14679,34,4975,32,1409,13,8159,28,3.909444,371.873767,12572,16079,9200,31176,10059,1296
2020-07-03,981,7701,112,14652,17,4603,34,1463,3,7470,30,3.952293,373.958955,10040,13643,11368,27494,12213,1485
2020-07-04,769,7086,82,13443,22,3865,27,1307,0,6772,7,3.973709,381.409387,9452,10967,11084,28035,11015,1365
2020-07-05,814,7570,92,14032,15,3980,27,1298,3,7324,16,4.088452,390.358692,10893,12097,11356,26167,10542,1463
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-06-26,661,13189,88,16736,16,2309,141,5465,21,6201,1,5.589233,381.785490,14809,11197,7839,16795,10039,737
2022-06-27,1096,13994,130,18068,21,2422,188,6132,19,6725,49,5.193566,392.073554,15812,15066,8043,22489,9823,796
2022-06-28,961,13596,151,17458,21,2270,197,5964,44,6504,20,5.428599,386.791620,15095,14621,8002,17141,9461,740
2022-06-29,976,13290,132,17206,21,2288,174,5879,13,6350,30,5.199989,387.564905,14444,13959,8512,20400,9626,676
2022-06-30,891,11687,94,15307,18,1703,135,4643,15,5483,21,5.317742,375.471924,13070,12985,7763,13096,9132,674

In [9]:
df.to_csv('data.csv', index=False)